### ISSUE TITLE
CSP + pretty-text errors

### ISSUE THREAD

**Issue by pr000t** [paviliondev/discourse-custom-wizard#170]
Hello,

When loading a wizard page, there are many errors in the console resulting in blank page:

- `Refused to load the script 'https://xxx.xx/ember_jquery.js' because it violates the following Content Security Policy directive: "script-src https://xxx.xx/logs/ https://xxx.xx/sidekiq/ https://xxx.xx/mini-profiler-resources/ https://xxx.xx/assets/ https://xxx.xx/brotli_asset/ https://xxx.xx/extra-locales/ https://xxx.xx/highlight-js/ https://xxx.xx/javascripts/ https://xxx.xx/plugins/ https://xxx.xx/theme-javascripts/ https://xxx.xx/svg-sprite/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`
Same thing for `/pretty-text-bundle.js` whose are both not available at the root url. 

- ![Capture d’écran du 2021-12-25 10-11-00](https://user-images.githubusercontent.com/20946964/147381866-f4259a86-8ec8-442f-8b9c-a44dd44ed5a5.png)

- Also trying to load ressource `https://xxx.xx/assets/service-worker-15ecb0bbafbd67e8acd8856d55fda07c0684318c6176c750cb2507c12ffd2190.js.map` but receive a 404 from nginx directly.

**Comment by Xore** [comment]
same here

**Comment by XScorpion2** [comment]
The `ember_jquery.js` error can bee fixed by updating `views/layouts/wizard.html.erb` to use `<%= preload_script "vendor" %>` instead of `<%= preload_script "ember_jquery" %>`
The second error is a little different as `pretty-text/sanitizer` moved to `pretty-text/addon/sanitizer` and I'm not quite sure what code in this project is causing the wrong location to be pulled in. Ruby and JS are not something I use regularly.
